port:               4004
title:              Smartdown Blog
email:              your-email@example.com
description:        A Blog Theme by Start Bootstrap adapted for Smartdown
author:             Your Name
url:                "https://yourgithubname.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    BlackrockDigital
facebook_username:  StartBootstrap
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
# remote_theme: BlackrockDigital/startbootstrap-clean-blog-jekyll # mmistakes/minimal-mistakes
theme: jekyll-theme-clean-blog
markdown:           kramdown
markdown_ext:       markdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

excerpt_separator: <!--more-->

include:
  - posts
  - pages
exclude:
  - Gemfile
  - Gemfile.lock
  - dist
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _hide/
  - README.md
  - targets/mm/
  - targets/legacy/
  - "*.sh"



collections:
  posts:
    output: true
    permalink: /posts/:title/
  rawposts:
    output: true
    permalink: /posts/:title
  pages:
    output: true
    permalink: /pages/:title/
  rawpages:
    output: true
    permalink: /pages/:title
  # about:
  #   output: true


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
  - scope:
      path: "rawposts"
      type: "posts"
    values:
      layout: "raw"
  - scope:
      path: "rawpages"
      type: "pages"
    values:
      layout: "raw"
