port:               4005
ga: true
safe: false
title: BlogKit Example

# Set theme
# theme: stylish-portfolio-jekyll-theme # blog-kit-theme
remote_theme: vidhyav656/startbootstrap-stylish-portfolio-jekyll # blog-kit-remote_theme

markdown_ext: 'markdown'
excerpt_separator: <!--more-->

collections:
  posts:
    output: true
    permalink: /posts/:title/
  rawposts:
    output: true
    permalink: /posts/:title
  pages:
    output: true
    permalink: /pages/:title/
  rawpages:
    output: true
    permalink: /pages/:title

include:
  - posts/
  - pages/
  - assets/css/*
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # - targets/*
  - Gemfile*
  - "*.sh"
  - targets/cb/
  - targets/mm/
  - hide/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default_posts"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default_pages"

keep_files:
  - assets
  - posts
  - pages
  - categories
  - img

sass:
  style: compressed
  sass_dir: _sass
